if (typeof globalReqisterForAsyncInit !== 'undefined')
        globalReqisterForAsyncInit('p_ctl00_ctl00');
YUI().use('reportal-hitlist', function (Y) {
    Y.one('#p_ctl00_ctl00_hitlist').plug(Y.Reportal.HitList,
    {"version":"21.0.1338","singleViewApiUrl":"/reportal/8-b/SingleView/ac911638-3da8-430f-a236-e5f67247773d/7566d81f-dbea-426f-98f1-8676e2fa444c/s1?Preview=True\u0026language=9","singleViewFormsChunkApiUrl":"/reportal/8-b/SingleViewCenterQuestions/ac911638-3da8-430f-a236-e5f67247773d/7566d81f-dbea-426f-98f1-8676e2fa444c/s1/Start/{start}/Size/10?Preview=True\u0026language=9","singleViewTexts":{"REPORT_SINGLEVIEW_RESPONDENTOVERVIEW":"Respondent overview","REPORT_SINGLEVIEW_PRINT":"Print the current respondent","REPORT_SINGLEVIEW_CLOSE":"Close this overlay","REPORT_SINGLEVIEW_FILTER":"Filter questions","REPORT_SINGLEVIEW_NOTHINGFOUND":"No questions match your search","REPORT_SINGLEVIEW_PREVIOUS":"Previous","REPORT_SINGLEVIEW_PREVIOUSHINT":"Previous respondent","REPORT_SINGLEVIEW_NEXT":"Next","REPORT_SINGLEVIEW_NEXTHINT":"Next respondent","REPORT_SINGLEVIEW_OF":"{0} of {1}","REPORT_SINGLEVIEW_MORE":"{0} more","REPORT_SINGLEVIEW_ALTERNATIVES":"Answers alternatives:"},"hitlistData":null,"serviceUrl":"/reportal/8-b/Report/ac911638-3da8-430f-a236-e5f67247773d/HitList/7566d81f-dbea-426f-98f1-8676e2fa444c?DbType=Production\u0026Language=9","serviceUrlMetaData":"/reportal/8-b/Report/ac911638-3da8-430f-a236-e5f67247773d/HitListMetaData/7566d81f-dbea-426f-98f1-8676e2fa444c?DbType=Production\u0026Language=9","searchValues":[],"sortingPagingValues":null,"clientId":"p_ctl00_ctl00",
    "columns":[{"key":"q2","label":"Please take a photo from your current location","sortable":true,"allowHTML":true,"hiddenByDefault":false,"abbr":"Please take a photo from your current location","headerStyle":"","contentStyle":"","alternatingStyle":""},
               {"key":"title","label":"Add image title:","sortable":true,"allowHTML":true,"hiddenByDefault":false,"abbr":"Add image title:","headerStyle":"","contentStyle":"","alternatingStyle":""},
               {"key":"description","label":"Add image description:","sortable":true,"allowHTML":true,"hiddenByDefault":false,"abbr":"Add image description:","headerStyle":"","contentStyle":"","alternatingStyle":""},{"key":"tags","label":"Tags","sortable":true,"allowHTML":true,"hiddenByDefault":false,"abbr":"Tags","headerStyle":"","contentStyle":"","alternatingStyle":""},
               {"key":"SurveyLink1","label":"Survey Link (1)","sortable":true,"allowHTML":true,"hiddenByDefault":false,"abbr":"Survey Link (1)","headerStyle":"","contentStyle":"","alternatingStyle":""}],"componentId":"7566d81f-dbea-426f-98f1-8676e2fa444c","pageId":"15e0c3b3-1f91-4f34-847b-b112b5c1ede9","prevText":"","nextText":"","searchItems":[{"id":"q2","label":"Please take a photo from your current location","precode":null,"type":11,"autoCompleteContext":null,"autoCompleteValueInHidden":false},{"id":"title","label":"Add image title:","precode":null,"type":1,"autoCompleteContext":null,"autoCompleteValueInHidden":false},{"id":"description","label":"Add image description:","precode":null,"type":1,"autoCompleteContext":null,"autoCompleteValueInHidden":false},
               {"id":"tags","label":"Tags","precode":null,"type":4,"autoCompleteContext":"hitlistcriteria;7566d81f-dbea-426f-98f1-8676e2fa444c;tags","autoCompleteValueInHidden":true}],"preview":true,
    "allColumns":[{"key":"q2","label":"Please take a photo from your current location","sortable":true,"allowHTML":true,"hiddenByDefault":false,"abbr":"Please take a photo from your current location","headerStyle":"","contentStyle":"","alternatingStyle":""},{"key":"title","label":"Add image title:","sortable":true,"allowHTML":true,"hiddenByDefault":false,"abbr":"Add image title:","headerStyle":"","contentStyle":"","alternatingStyle":""},{"key":"description","label":"Add image description:","sortable":true,"allowHTML":true,"hiddenByDefault":false,"abbr":"Add image description:","headerStyle":"","contentStyle":"","alternatingStyle":""},{"key":"tags","label":"Tags","sortable":true,"allowHTML":true,"hiddenByDefault":false,"abbr":"Tags","headerStyle":"","contentStyle":"","alternatingStyle":""},{"key":"SurveyLink1","label":"Survey Link (1)","sortable":true,"allowHTML":true,"hiddenByDefault":false,"abbr":"Survey Link (1)","headerStyle":"","contentStyle":"","alternatingStyle":""}],"pageAjaxEnabled":true,"language":9,"hashedProjectId":"s1_98A2FE7DFCF1BD0F87E2067385823A17DA81BADE","showSingleViewOnRowSelect":false,"styles":{"table":"","header":"","cell":""},"captions":{"stoe":"Smaller than or equal","gtoe":"Greater than or equal","between":"Between","before":"Before","after":"After","exactly":"Exactly","showdefaultcols":"Show default columns","apply":"Apply","cancel":"Cancel","showhide":"Show / Hide columns","yes":"Yes","no":"No","loadingData":"Loading data, please wait...","checkall":"Check all","uncheckall":"Uncheck all","errorLoading":"Error loading data","errorNoColumns":"No columns selected"},"noInitialLoad":false});
});


